In [35]:
import numpy as np

In [37]:
# Given vectors V1 = (1, 2, 3) 
# and V2 = (2, 1, 3) 
# and a 3x3 matrix M = [(2, 1, 3), (1, 2, 1), (1, 0, 2)], 

V1 = np.array([1, 2, 3])
V2 = np.array([2, 1, 3])
M = np.matrix([[2,1,3],[1,2,1],[1,0,2]])

In [38]:
# compute: V2 – V1
V2-V1

array([ 1, -1,  0])

In [39]:
# compute: V2 + V1
V2+V1

array([3, 3, 6])

In [40]:
# compute: |V1|
np.linalg.norm(V1)

3.7416573867739413

In [41]:
# compute: |V2|
np.linalg.norm(V2)

3.7416573867739413

In [42]:
# compute: M * V1 (matrix times vector, transpose it as necessary
M * np.transpose(V1[np.newaxis])

matrix([[13],
        [ 8],
        [ 7]])

In [43]:
# compute: M * M (or M^2)
M**2

matrix([[ 8,  4, 13],
        [ 5,  5,  7],
        [ 4,  1,  7]])

In [44]:
# compute: M^3
M**3

matrix([[33, 16, 54],
        [22, 15, 34],
        [16,  6, 27]])

In [45]:
# c) Suppose we are flipping a coin with Head (H) and Tail (T) sides. 
# The coin is not balanced with 0.6 probability of H coming up (and 0.4 of T). 
#Compute the probabilities of getting:

#HTTT

0.6 * 0.4 * 0.4 * 0.4

0.038400000000000004

In [46]:
# THTT

0.4 * 0.6 * 0.4 * 0.4

0.038400000000000004

In [50]:
# Exactly 1 Head out of a sequence of 4 coin flips.
# HTTT THTT TTHT TTTH

# Each combination has the same probability, simply add the probabilities
(0.6 * 0.4 * 0.4 * 0.4) + (0.4 * 0.6 * 0.4 * 0.4) + (0.4 * 0.4 * 0.6 * 0.4) + (0.4 * 0.4 * 0.4 * 0.6)

0.15360000000000004

In [51]:
# Exactly 1 Tail out of sequence of 4 coin flips.
# THHH HTHH HHTH HHHT

# Each combination has the same probability, simply add the probabilities
(0.4 * 0.6 * 0.6 * 0.6) + (0.6 * 0.4 * 0.6 * 0.6) + (0.6 * 0.6 * 0.4 * 0.6) + (0.6 * 0.6 * 0.6 * 0.4)

0.3456